name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Format code
        uses: Jerome1337/gofmt-action@v1.0.5

      - name: Setup gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

      - name: Test
        run: make test
